---
name: cron
on:
  schedule:
    - cron: "13 13 * * *"
concurrency:
  group: cron
  cancel-in-progress: true
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle install
      - run: |
          bin/fief --verbose --token ${{ secrets.TOKEN }} --to gh-pages --delay 100 \
            --include jcabi/* \
            --exclude jcabi/.github \
            --include yegor256/* \
            --include sttc/* \
            --include objectionary/* \
            --include polystat/* \
            --include zerocracy/* \
            --include zold-io/*
      - run: mkdir -p gh-pages/$(date +'%Y/%m/%d')
      - run: cp gh-pages/index.xml gh-pages/$(date +'%Y/%m/%d')/index.xml
      - uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
