---
name: xcop
on:
  push:
  pull_request:
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: g4s8/xcop-action@master
